paths:
  input_dir: "/home/lpnhe/grand/grand/analysis/pipeline_nathan/mock_inputs/gp80/GrandRoot/2026/09"
  output_dir: "/home/lpnhe/grand/grand/analysis/pipeline_nathan/outputs"
  rtk_antenna_positions_path: "/home/lpnhe/grand/grand/analysis/example/RTK_pos/rtk_pos_gp65_from_xls_gdl.csv"
  nutrig_template_path: "/home/lpnhe/grand/grand/analysis/pipeline_nathan/templates_ZHAireS_DC2.1rc4_RAW_XY_THRESH_100_5.txt"
  plot_dir: "/home/lpnhe/grand/grand/analysis/pipeline_nathan/analysis/plots"
  sanity_plot_dir: "/home/lpnhe/grand/grand/analysis/pipeline_nathan/analysis/sanity_plots"
  grandlib_path: "/home/lpnhe/grand"
  nl_style_path: "/home/lpnhe/Documents/Nutrig_analysis/runs/nl_style"
  nutrig_src_path: "/home/lpnhe/nutrig/src"
  nutrig_templates_npz_path: "/home/lpnhe/grand/grand/analysis/pipeline_nathan/templates_ZHAireS_DC2.1rc4_RAW_XY_THRESH_100_5.npz"

logging:
  level: "DEBUG"
  log_file: null

cuts:
  nant_cut:
    threshold: 5
  nutrig_cut:
    rho_min_threshold: 0.5
    rho_mean_threshold: 0.7
  chi2_adf_cut:
    threshold: 25.0

